<?
//RENAME TO .env.local.php

return [
    'SENDGRID_USERNAME'    => 'SENDGRID USERNAME',
    'SENDGRID_PASSWORD'    => 'SENDGRID PASSWORD',
    'CONTEXTIO_ACCOUNT_ID' => 'NOT REQUIRED FOR SENDGRID SUPPPORT',
    'CONTEXTIO_KEY'        => 'NOT REQUIRED FOR SENDGRID SUPPPORT',
    'CONTEXTIO_SECRET'     => 'NOT REQUIRED FOR SENDGRID SUPPPORT',
];
